show databases;
CREATE DATABASE IF NOT EXISTS DBName;
CREATE TABLE IF NOT EXISTS CUSTOMERS(
   ID   INT              NOT NULL,
   NAME VARCHAR (20)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  CHAR (25) ,
   SALARY   DECIMAL (18, 2),       
   PRIMARY KEY (ID)
);

INSERT INTO CUSTOMERS VALUES ( 1 , 'SAKET' , 1 , "SAGAR" , 22 );
